In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
# print(arr)

## default array creation 
# print(np.zeros(3))
a = np.ones((2,3))
# print(a)


# create a array with desire number
b = np.full((2,3),5)
# print(b)

# creating sequence of numbers in numpy

arr1 = np.arange(1,20,3)
print(arr1)

# creating identity matrix

identity = np.eye(4) #argument-> size
print(identity)





[ 1  4  7 10 13 16 19]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
import numpy as np

# checking the shape and total number of element in the array of the array

arr2d = np.array([[1,2,3],[4,5,6]])
# print(arr2d.shape)
# print(arr2d.size)

# check the dimension of the array
# print(arr2d.ndim)

# check the type of the array element
print(arr2d.dtype)

# type conversion of the element

arr = np.array([1.2,3.4,5.6])
int_arr = arr.astype(int)

print(int_arr)
print(int_arr.dtype)


int64
[1 3 5]
int64


## Aggregation functions

In [3]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
50
14.142135623730951
200.0


## Indexing and slicing


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
# print(arr[1])

arr1 = np.array([[1,2],[3,4]])
# print(arr1[1,1])

print(arr[1:5])

#fancy indexing

print(arr[[0,2,4]])

# boolean masking or filtering

print(arr[arr>1])

[2 3 4 5]
[1 3 5]
[2 3 4 5]


## Reshaping and manipulating

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
# for converting or reshaping of a 1d_array  into multidimensional_array
reshaped= arr.reshape(2,4)
# print(reshaped)

# converting a multidimensional array into 1d_array with without copy and with copy

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d.ravel()) #it returns the view
print(arr2d.flatten()) #it returns copy of the original array



[1 2 3 4 5 6]
[1 2 3 4 5 6]


## Array Modification

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
# print(arr)
new_arr = np.insert(arr, 2, 10)
# print(new_arr)

arr2d = np.array([[1,2],[3,4]])
new_arr2d = np.insert(arr2d,1,[5,6],axis = 0)
# print(new_arr2d)

# add element at the end of the array
arr1 = np.append(arr,[6,7,8])
# print(arr1)

# merge two arrays

arr2 = np.array([4,5,6,7])
new_arr = np.concatenate((arr,arr2))
print(new_arr)

# deletion of element in array

deletion = np.delete(arr,0)
print(deletion)

arr2d = np.array([[1,2,3],[4,5,6]])
new_arr2 =np.delete(arr2d,0,axis = 0)
print(new_arr2)



[1 2 3 4 5 4 5 6 7]
[2 3 4 5]
[[4 5 6]]


## Stacking


In [9]:
# vertically stack

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack((arr1,arr2)))


# horizontally stack

print(np.hstack((arr1,arr2)))



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## Splitting

In [10]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(np.split(arr,2))



[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


## Broadcasting

In [15]:
import numpy as np
prices = np.array([100,200,300])

discount = 10

final_prices = prices - (prices * discount/100)

# print(final_prices)

# print(prices*2)

# 1d array to 2d array
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])

result = matrix + vector
print(result)





[[11 22 33]
 [14 25 36]]


## Vectorization
# Do the mathematical operation on entire array at once

In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
multiplied = arr * 30
print(multiplied)

[ 30  60  90 120 150 180 210 240]


## Handling missing values

In [20]:
# isnan()- detect missing values

# we don't compare it (np.nan == np.nan)

import numpy as np
array = np.array([1,2,3,np.nan,4,5,6,np.nan])
# print(np.isnan(array))


# np.nan_to_num() - it replace the nan to number

cleaned_arr = np.nan_to_num(array, nan = 100)
print(cleaned_arr)

# np.isinf() - it check the infinity value in the array

arr = np.array([1,2,np.inf,5,7])
print(np.isinf(arr))


[  1.   2.   3. 100.   4.   5.   6. 100.]
[False False  True False False]
