In [2]:
import numpy as np

Advance operation with Business examples

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 170000, 190000, 210000], #Paradise Biryani
    [2, 130000, 180000, 150000, 250000], #Baba Biryani
    [3, 120000, 150000, 120000, 230000], #Chandu Biryani
    [4, 110000, 160000, 150000, 220000], #KFC Biryani
    [5, 160000, 120000, 100000, 210000], #Rakesh Biryani

])

print("==== zepto analysis ====")

print("\n sales data shape", sales_data.shape)

print("\n sample data for first 3 restaurant", sales_data[:3])

print("\n sample data for all", sales_data[:,1 :])




==== zepto analysis ====

 sales data shape (5, 5)

 sample data for first 3 restaurant [[     1 150000 170000 190000 210000]
 [     2 130000 180000 150000 250000]
 [     3 120000 150000 120000 230000]]

 sample data for all [[150000 170000 190000 210000]
 [130000 180000 150000 250000]
 [120000 150000 120000 230000]
 [110000 160000 150000 220000]
 [160000 120000 100000 210000]]


In [5]:
# total sales per year row column

print(np.sum(sales_data, axis = 0))

yearly_sales = np.sum(sales_data[: ,1 :],axis = 1)
print(yearly_sales)

#minimum sales per year

print(np.min(sales_data[:,1:], axis = 1))


# maximum sales per year

max_sales = np.max(sales_data[:,1:], axis = 0)
print(max_sales)


#Average sales

avg_sales = np.mean(sales_data[:,1:],axis = 1)
print(avg_sales)




[     15  670000  780000  710000 1120000]
[720000 710000 620000 640000 590000]
[150000 130000 120000 110000 100000]
[160000 180000 190000 250000]
[180000. 177500. 155000. 160000. 147500.]


In [7]:
#cumulative sales
cum_sum = np.cumsum(sales_data[:,1:],axis = 1)
print(cum_sum)

[[150000 320000 510000 720000]
 [130000 310000 460000 710000]
 [120000 270000 390000 620000]
 [110000 270000 420000 640000]
 [160000 280000 380000 590000]]
